FROM python:3.12-slim

# Install system dependencies
RUN apt-get update && apt-get install -y libmagic1 && rm -rf /var/lib/apt/lists/*

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Copy pyproject for caching
COPY pyproject.toml .

# Install runtime + test dependencies
RUN pip install --upgrade pip \
    && pip install "fastapi>=0.124.4" "uvicorn>=0.38.0" "celery>=5.6.0" "redis>=7.1.0" "sqlalchemy>=2.0.45" "pydantic>=2.12.5" \
    && pip install --no-cache-dir pytest pytest-cov fakeredis httpx


COPY . /app

EXPOSE 8020

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8020"]
